version: '3.9'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pipeimob
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://user:pass@db:5432/pipeimob
      API_SECRET_KEY: changeme123
    ports:
      - "8000:8000"

volumes:
  pgdata:
