"""add_enums_coluns

Revision ID: 86c42f615fd2
Revises: 9d7beb59ffc3
Create Date: 2025-08-26 00:12:13.595044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c42f615fd2'
down_revision: Union[str, Sequence[str], None] = '9d7beb59ffc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    partytype_enum = sa.Enum('BUYER', 'SELLER', 'BROKER', name='partytype')
    partytype_enum.create(op.get_bind(), checkfirst=True)

    transactionstatus_enum = sa.Enum(
        'CREATED', 'UNDER_ANALYSIS', 'APPROVED', 'COMPLETED', 'CANCELLED', name='transactionstatus'
    )
    transactionstatus_enum.create(op.get_bind(), checkfirst=True)   

    op.drop_constraint('commissions_transaction_id_fk_fkey', 'commissions', type_='foreignkey')
    op.create_foreign_key(None, 'commissions', 'transactions', ['transaction_id_fk'], ['transaction_id'])
    op.add_column('parties', sa.Column(
        'type', partytype_enum, nullable=False)
        )
    op.drop_constraint('parties_transaction_id_fk_fkey', 'parties', type_='foreignkey')
    op.create_foreign_key(None, 'parties', 'transactions', ['transaction_id_fk'], ['transaction_id'])
    op.add_column(
        'transactions', sa.Column('status', transactionstatus_enum, nullable=False
        )
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'status')
    op.drop_constraint(None, 'parties', type_='foreignkey')
    op.create_foreign_key(
        'parties_transaction_id_fk_fkey', 'parties', 'transactions', ['transaction_id_fk'], ['transaction_id'], 
        ondelete='CASCADE'
    )
    op.drop_column('parties', 'type')
    op.drop_constraint(None, 'commissions', type_='foreignkey')
    op.create_foreign_key(
        'commissions_transaction_id_fk_fkey', 'commissions', 'transactions', ['transaction_id_fk'], ['transaction_id'], 
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
