"""create_tables

Revision ID: bd10d95331c8
Revises: 
Create Date: 2025-08-27 03:07:43.403974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd10d95331c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('property_code', sa.String(), nullable=False),
    sa.Column('sale_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UNDER_ANALYSIS', 'APPROVED', 'COMPLETED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('commissions',
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id_fk', sa.UUID(), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id_fk'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('commission_id')
    )
    op.create_table('parties',
    sa.Column('party_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id_fk', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BUYER', 'SELLER', 'BROKER', name='partytype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id_fk'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('party_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parties')
    op.drop_table('commissions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
